#!/usr/bin/env python
"""
Script que permite realizar extracciones del servido de seiscomp mediante el servicio web fdsn
"""
from obspy import UTCDateTime
from obspy.fdsn.client import Client
import sys

ip_fdsn = "http://10.100.100.232"
port_fdsn = "8091"
Format = "mseed"

def archive_name(lista):
	name = ""
	for l in lista:
		if ('*' in l )== False:
			name += "_"+l
		elif ('*' in l)== True:
			name += "_"+l.strip('*')
		else:
			name += "_"
	return name

if len(sys.argv) < 2:
	print "No hay parametros de entrada"
	sys.exit()
if len(sys.argv) > 10:
	print "Demasiados argumentos"
	sys.exit()
year, MM, dd, hh, mm, ss = int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4][0:2]), int(sys.argv[4][2:4]), int(sys.argv[4][4:6])

t = UTCDateTime(year, MM, dd, hh, mm, ss)
t_ = float(sys.argv[5])

if len(sys.argv)>2:
	name = str(year)+"-"+str(MM)+"-"+str(dd)+"-"+str(hh)+str(mm)+archive_name(sys.argv[3:])+"."+Format
else:
	name = str(year)+"-"+str(MM)+"-"+str(dd)+"-"+str(hh)+str(mm)+"."+Format 

print t, t_


client = Client(ip_fdsn+":"+port_fdsn)
print client



if len(sys.argv) == 6:
	st = client.get_waveforms("CM", "*", "?0", "*", t, t+t_)
	print st

if len(sys.argv) == 7:
	st = client.get_waveforms(sys.argv[6], "*", "*", "*", t, t+t_)
        print st

if len(sys.argv) == 8:
	st = client.get_waveforms(sys.argv[6], sys.argv[7], "*", "*", t, t+t_)
        print st

if len(sys.argv) == 9:
	st = client.get_waveforms(sys.argv[6], sys.argv[7], sys.argv[8], "*", t, t+t_)
        print st
if len(sys.argv) == 10:
	st = client.get_waveforms(sys.argv[6], sys.argv[7], sys.argv[8], sys.argv[9], t, t+t_)
        print st

st.write(name, Format)
	
