#!/usr/bin/env python
"""
Script que permite realizar extracciones del servido de seiscomp mediante el servicio web fdsn
para cada turno
v(1) Nelson David Perez e-mail: nperez@sgc.gov.co
"""
from obspy import UTCDateTime
from obspy.fdsn.client import Client
from datetime import timedelta
import sys


#Se define url del servidor, puerto y formato

ip_fdsn = "http://10.100.100.232"
port_fdsn = "8091"
Format = "mseed"
dt = timedelta(minutes=12)
two = timedelta(minutes=2)
#funcion que crea un nombre a partir de parametros de entrada
def archive_name(lista):
	name = ""
	for l in lista:
		if ('*' in l )== False:
			name += "_"+l
		elif ('*' in l)== True:
			name += "_"+l.strip('*')
		else:
			name += "_"
	return name
#Se revisan los parametros de entrada

if len(sys.argv) < 5:
	print "Faltan parametros de entrada"
	sys.exit()
if len(sys.argv) > 5:
	print "Demasiados argumentos"
	sys.exit()
year, MM, dd = sys.argv[1], sys.argv[2], sys.argv[3]
turno = sys.argv[4]

#Se define el tiempo y el nombre de la traza

if turno == '1':
	t = UTCDateTime(int(year), int(MM), int(dd), 00, 00, 00)
	Dt = timedelta(hours=10)
elif turno == '2':
	t = UTCDateTime(int(year), int(MM), int(dd), 10, 00, 00)
	Dt = timedelta(hours=10)
elif turno == '3':
	t = UTCDateTime(int(year), int(MM), int(dd), 20, 00, 00)
	Dt = timedelta(hours=4)
else:
	print "Argumento no valido"
	sys.exit()
	
t_fin = t + Dt

#Se inicia el cliente FDSN para la solicitud
client = Client(ip_fdsn+":"+port_fdsn)

while t < t_fin:
	st = client.get_waveforms("*", "*", "*", "*", t-two, t+dt)
	st.merge(method=0, fill_value='interpolate', interpolation_samples=0)
	time = str(t-two).split('T')[1].split('.')[0].split(":")
	hh, mm, ss = time[0], time[1], time[2]
	name = year+"-"+MM+"-"+dd+"-"+hh+mm+"-"+ss+"M.COL___"+str(len(st))
	print name
	t += dt
	st.write(name, Format)
	
